import 'position.dart';

class PositionWeights {
  static final Map<FootballPlayerAbstractPosition, Map<FootballPlayerAbstractPosition, double>> weights = {
    FootballPlayerAbstractPosition.gk: {
      FootballPlayerAbstractPosition.gk: 1.0,
      // Вратарь не может играть на других позициях
      FootballPlayerAbstractPosition.cb: 0.0,
      FootballPlayerAbstractPosition.lb: 0.0,
      FootballPlayerAbstractPosition.rb: 0.0,
      FootballPlayerAbstractPosition.dm: 0.0,
      FootballPlayerAbstractPosition.cm: 0.0,
      FootballPlayerAbstractPosition.am: 0.0,
      FootballPlayerAbstractPosition.lm: 0.0,
      FootballPlayerAbstractPosition.rm: 0.0,
      FootballPlayerAbstractPosition.lw: 0.0,
      FootballPlayerAbstractPosition.rw: 0.0,
      FootballPlayerAbstractPosition.cf: 0.0,
      FootballPlayerAbstractPosition.st: 0.0,
    },
    FootballPlayerAbstractPosition.cb: {
      FootballPlayerAbstractPosition.cb: 1.0,
      FootballPlayerAbstractPosition.lb: 0.9,
      FootballPlayerAbstractPosition.rb: 0.9,
      FootballPlayerAbstractPosition.dm: 0.9,
      FootballPlayerAbstractPosition.cm: 0.8,
      FootballPlayerAbstractPosition.lm: 0.6,
      FootballPlayerAbstractPosition.rm: 0.6,
      FootballPlayerAbstractPosition.am: 0.5,
      FootballPlayerAbstractPosition.lw: 0.5,
      FootballPlayerAbstractPosition.rw: 0.5,
      FootballPlayerAbstractPosition.cf: 0.5,
      FootballPlayerAbstractPosition.st: 0.5,
      FootballPlayerAbstractPosition.gk: 0.0,
    },
    FootballPlayerAbstractPosition.lb: {
      FootballPlayerAbstractPosition.lb: 1.0,
      FootballPlayerAbstractPosition.cb: 0.9,
      FootballPlayerAbstractPosition.rb: 0.9,
      FootballPlayerAbstractPosition.lm: 0.9,
      FootballPlayerAbstractPosition.lw: 0.8,
      FootballPlayerAbstractPosition.dm: 0.7,
      FootballPlayerAbstractPosition.rm: 0.7,
      FootballPlayerAbstractPosition.cm: 0.6,
      FootballPlayerAbstractPosition.am: 0.6,
      FootballPlayerAbstractPosition.rw: 0.6,
      FootballPlayerAbstractPosition.cf: 0.5,
      FootballPlayerAbstractPosition.st: 0.5,
      FootballPlayerAbstractPosition.gk: 0.0,
    },
    FootballPlayerAbstractPosition.rb: {
      FootballPlayerAbstractPosition.rb: 1.0,
      FootballPlayerAbstractPosition.cb: 0.9,
      FootballPlayerAbstractPosition.lb: 0.9,
      FootballPlayerAbstractPosition.rm: 0.9,
      FootballPlayerAbstractPosition.rw: 0.8,
      FootballPlayerAbstractPosition.dm: 0.7,
      FootballPlayerAbstractPosition.lm: 0.7,
      FootballPlayerAbstractPosition.cm: 0.6,
      FootballPlayerAbstractPosition.am: 0.6,
      FootballPlayerAbstractPosition.lw: 0.6,
      FootballPlayerAbstractPosition.cf: 0.5,
      FootballPlayerAbstractPosition.st: 0.5,
      FootballPlayerAbstractPosition.gk: 0.0,
    },
    FootballPlayerAbstractPosition.dm: {
      FootballPlayerAbstractPosition.dm: 1.0,
      FootballPlayerAbstractPosition.cb: 0.9,
      FootballPlayerAbstractPosition.rb: 0.8,
      FootballPlayerAbstractPosition.lb: 0.8,
      FootballPlayerAbstractPosition.cm: 0.9,
      FootballPlayerAbstractPosition.am: 0.7,
      FootballPlayerAbstractPosition.lm: 0.7,
      FootballPlayerAbstractPosition.rm: 0.7,
      FootballPlayerAbstractPosition.lw: 0.6,
      FootballPlayerAbstractPosition.rw: 0.6,
      FootballPlayerAbstractPosition.cf: 0.5,
      FootballPlayerAbstractPosition.st: 0.5,
      FootballPlayerAbstractPosition.gk: 0.0,
    },
    FootballPlayerAbstractPosition.cm: {
      FootballPlayerAbstractPosition.cm: 1.0,
      FootballPlayerAbstractPosition.cb: 0.9,
      FootballPlayerAbstractPosition.rb: 0.8,
      FootballPlayerAbstractPosition.lb: 0.8,
      FootballPlayerAbstractPosition.dm: 0.9,
      FootballPlayerAbstractPosition.am: 0.9,
      FootballPlayerAbstractPosition.lm: 0.7,
      FootballPlayerAbstractPosition.rm: 0.7,
      FootballPlayerAbstractPosition.lw: 0.6,
      FootballPlayerAbstractPosition.rw: 0.6,
      FootballPlayerAbstractPosition.cf: 0.6,
      FootballPlayerAbstractPosition.st: 0.5,
      FootballPlayerAbstractPosition.gk: 0.0,
    },
    FootballPlayerAbstractPosition.am: {
      FootballPlayerAbstractPosition.am: 1.0,
      FootballPlayerAbstractPosition.lw: 0.8,
      FootballPlayerAbstractPosition.rw: 0.8,
      FootballPlayerAbstractPosition.cf: 0.8,
      FootballPlayerAbstractPosition.st: 0.8,
      FootballPlayerAbstractPosition.cm: 0.7,
      FootballPlayerAbstractPosition.lm: 0.7,
      FootballPlayerAbstractPosition.rm: 0.7,
      FootballPlayerAbstractPosition.dm: 0.6,
      FootballPlayerAbstractPosition.cb: 0.5,
      FootballPlayerAbstractPosition.rb: 0.5,
      FootballPlayerAbstractPosition.lb: 0.5,
      FootballPlayerAbstractPosition.gk: 0.0,
    },
    FootballPlayerAbstractPosition.lm: {
      FootballPlayerAbstractPosition.lm: 1.0,
      FootballPlayerAbstractPosition.lb: 0.9,
      FootballPlayerAbstractPosition.lw: 0.9,
      FootballPlayerAbstractPosition.rm: 0.8,
      FootballPlayerAbstractPosition.am: 0.8,
      FootballPlayerAbstractPosition.rw: 0.7,
      FootballPlayerAbstractPosition.cf: 0.7,
      FootballPlayerAbstractPosition.st: 0.7,
      FootballPlayerAbstractPosition.cm: 0.6,
      FootballPlayerAbstractPosition.dm: 0.6,
      FootballPlayerAbstractPosition.cb: 0.5,
      FootballPlayerAbstractPosition.rb: 0.5,
      FootballPlayerAbstractPosition.gk: 0.0,
    },
    FootballPlayerAbstractPosition.rm: {
      FootballPlayerAbstractPosition.rm: 1.0,
      FootballPlayerAbstractPosition.rb: 0.9,
      FootballPlayerAbstractPosition.rw: 0.9,
      FootballPlayerAbstractPosition.lw: 0.8,
      FootballPlayerAbstractPosition.cf: 0.8,
      FootballPlayerAbstractPosition.st: 0.8,
      FootballPlayerAbstractPosition.am: 0.8,
      FootballPlayerAbstractPosition.lm: 0.7,
      FootballPlayerAbstractPosition.cm: 0.6,
      FootballPlayerAbstractPosition.dm: 0.6,
      FootballPlayerAbstractPosition.cb: 0.5,
      FootballPlayerAbstractPosition.lb: 0.5,
      FootballPlayerAbstractPosition.gk: 0.0,
    },
    FootballPlayerAbstractPosition.lw: {
      FootballPlayerAbstractPosition.lw: 1.0,
      FootballPlayerAbstractPosition.cf: 0.9,
      FootballPlayerAbstractPosition.st: 0.9,
      FootballPlayerAbstractPosition.lm: 0.9,
      FootballPlayerAbstractPosition.rw: 0.8,
      FootballPlayerAbstractPosition.rm: 0.8,
      FootballPlayerAbstractPosition.am: 0.8,
      FootballPlayerAbstractPosition.lb: 0.7,
      FootballPlayerAbstractPosition.cm: 0.7,
      FootballPlayerAbstractPosition.dm: 0.6,
      FootballPlayerAbstractPosition.cb: 0.5,
      FootballPlayerAbstractPosition.rb: 0.5,
      FootballPlayerAbstractPosition.gk: 0.0,
    },
    FootballPlayerAbstractPosition.rw: {
      FootballPlayerAbstractPosition.rw: 1.0,
      FootballPlayerAbstractPosition.cf: 0.9,
      FootballPlayerAbstractPosition.st: 0.9,
      FootballPlayerAbstractPosition.rm: 0.9,
      FootballPlayerAbstractPosition.lm: 0.8,
      FootballPlayerAbstractPosition.lw: 0.8,
      FootballPlayerAbstractPosition.am: 0.8,
      FootballPlayerAbstractPosition.rb: 0.7,
      FootballPlayerAbstractPosition.cm: 0.7,
      FootballPlayerAbstractPosition.dm: 0.6,
      FootballPlayerAbstractPosition.cb: 0.5,
      FootballPlayerAbstractPosition.lb: 0.5,
      FootballPlayerAbstractPosition.gk: 0.0,
    },
    FootballPlayerAbstractPosition.cf: {
      FootballPlayerAbstractPosition.cf: 1.0,
      FootballPlayerAbstractPosition.st: 1.0,
      FootballPlayerAbstractPosition.am: 0.9,
      FootballPlayerAbstractPosition.lw: 0.9,
      FootballPlayerAbstractPosition.rw: 0.9,
      FootballPlayerAbstractPosition.lm: 0.7,
      FootballPlayerAbstractPosition.rm: 0.7,
      FootballPlayerAbstractPosition.cm: 0.7,
      FootballPlayerAbstractPosition.dm: 0.6,
      FootballPlayerAbstractPosition.cb: 0.5,
      FootballPlayerAbstractPosition.rb: 0.5,
      FootballPlayerAbstractPosition.lb: 0.5,
      FootballPlayerAbstractPosition.gk: 0.0,
    },
    FootballPlayerAbstractPosition.st: {
      FootballPlayerAbstractPosition.st: 1.0,
      FootballPlayerAbstractPosition.cf: 1.0,
      FootballPlayerAbstractPosition.am: 0.9,
      FootballPlayerAbstractPosition.lw: 0.9,
      FootballPlayerAbstractPosition.rw: 0.9,
      FootballPlayerAbstractPosition.lm: 0.7,
      FootballPlayerAbstractPosition.rm: 0.7,
      FootballPlayerAbstractPosition.cm: 0.7,
      FootballPlayerAbstractPosition.dm: 0.6,
      FootballPlayerAbstractPosition.cb: 0.5,
      FootballPlayerAbstractPosition.rb: 0.5,
      FootballPlayerAbstractPosition.lb: 0.5,
      FootballPlayerAbstractPosition.gk: 0.0,
    },
  };

  static double getWeight(FootballPlayerAbstractPosition? first, FootballPlayerAbstractPosition? second) {
    if (first == null || second == null) {
      return 0.0;
    }

    return weights[first]![second]!;
  }
}
