// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxO05saK_q0o5dkvUZYJRQkfhCL4pXzy4',
    appId: '1:590271846043:web:55bec345a0cc9b4291583e',
    messagingSenderId: '590271846043',
    projectId: 'football-collection-c7c28',
    authDomain: 'football-collection-c7c28.firebaseapp.com',
    storageBucket: 'football-collection-c7c28.firebasestorage.app',
    measurementId: 'G-PC62WVQQGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYJB_It0Pa6yEe-S6-DfvganqyMQF_Pfo',
    appId: '1:590271846043:android:dc3bb93b3890c7b791583e',
    messagingSenderId: '590271846043',
    projectId: 'football-collection-c7c28',
    storageBucket: 'football-collection-c7c28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEiVOBHzCABUeaEsWfq42sf74O_X_rbsI',
    appId: '1:590271846043:ios:26226391de864b4b91583e',
    messagingSenderId: '590271846043',
    projectId: 'football-collection-c7c28',
    storageBucket: 'football-collection-c7c28.firebasestorage.app',
    iosBundleId: 'com.dosbrosdev.footballCollection',
  );

}